#!/bin/bash
while getopts i:g:s flag
do
  case "${flag}" in
    i) infile=${OPTARG};;
    g) outdir=${OPTARG};;
    s) dataflow=true;;
  esac
done

if [ "$dataflow" = true ] ; then 
  python3 ./analysis.py -i $infile -s
  exit 0
fi
python3 ./analysis.py -i $infile -g $outdir